import type { Metadata } from "next";
import { Geist, JetBrains_Mono } from "next/font/google";
import Header from "@/components/Header";
import SocialDockWrapper from "@/components/SocialDockWrapper";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const jetBrainsMono = JetBrains_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ChessX Tech Solution | Engineered for the next generation of web hardware.",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${jetBrainsMono.variable} antialiased`}
      >
        <Header />
        {children}
        <SocialDockWrapper />
      </body>
    </html>
  );
}
